<img src="img/viu_logo.png" width="200">

## 01MIAR - NumPy

![logo](img/python_logo.png)

*Ivan Fuertes / Franklin Alvarez*

# NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [17]:
import sys
!{sys.executable} -m pip install --upgrade pip

In [18]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:


import numpy as np
print(np.__version__)


2.4.4


In [ ]:
!-m pip install --upgrade pip   
!pip show numpy

import sys
!{sys.executable} -m pip install numpy

!pip list
!pip install numpy

In [21]:
#importar libreria
import numpy as np

## Performance Sample, NumPy vs Plain Python

In [23]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 3.16 s
Wall time: 3.46 s


In [24]:
my_arr = np.arange(10000000)  # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: total: 78.1 ms
Wall time: 82.4 ms


## Formas de crear ndarrays

In [25]:
array = np.array([ [2,71,0,34], [2,171,-35, 50] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  50]]


In [26]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [ ]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,11,1.5))    # array a partir de una secuencia(range) 1D

In [ ]:
# Generar arrays con valores fijos

# print(np.zeros((2, 3)))       # 1D
# print(np.ones((2,2)))    # matrix 2x2
# print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
# print(np.full((5,2),3)) # matrix 5x2 llena del valor 3
print(np.eye(3))         # matrix identity

## Obtener información sobre ndarray

 * Valores máximos y mínimos

In [ ]:
my_1darray = np.array([2,71,0,34])
my_2darray = np.array([ [2,71,0,34], [2,171,-35,34] ])

print(my_1darray)
print(my_2darray)

In [ ]:
print("Índice máximo:", my_2darray.argmax())    # índice del valor más alto
print("Valor máximo:", my_2darray.max())

print("Índice mínimo:", my_2darray.argmin())    # índice del valor más alto
print("Valor mínimo:", my_2darray.min())

print("Índices no nulos:", my_1darray.nonzero())   # retorna los índices de los elementos distintos a 0

In [ ]:
# Si el array es de varias dimensiones, retorna un array por cada dimensión
print("Índices no nulos:", my_2darray.nonzero())

i_filas, i_columnas = my_2darray.nonzero()
print("Índice filas:", i_filas)
print("Índice columnas:", i_columnas)

# print( "Coordenadas:", [ (int(i_filas[i]), int(i_columnas[i])) for i in range(len(i_filas))] )

In [ ]:
# Otra forma de obtener max o min con métodos de la librería

print("Valor máximo:", np.max(my_1darray))    # np.max() es equivalente a np.amax()
# print("Valor mínimo:", np.min(my_1darray))

 * Número de elementos, tamaño y forma del array

In [ ]:
my_3darray = np.full((5, 2, 2), -3) # matrix 5x2x2 llena del valor -3

print(my_3darray)
print("Número de elementos:", my_3darray.size)        # número de elementos
print("Forma:", my_3darray.shape)                     # dimensiones
print("Dimensiones:", my_3darray.ndim)                # número de dimensiones

In [32]:
print("Forma:", my_1darray.shape)                     # La forma de un array unidimensional es una tupla de un valor

NameError: name 'my_1darray' is not defined

#### Redimensionar los datos

In [33]:
array1d = np.array([10, 71, 21, 19, 213, 412, 111, 98]) # Array de una dimensión
print(array1d)
print("Forma:", array1d.shape)
print("Dimensiones:", array1d.ndim)

array2d = array1d.reshape(1,8)                          # Array de dos dimensiones

print(array2d)
print("Forma:", array2d.shape)
print("Dimensiones:", array2d.ndim)

[ 10  71  21  19 213 412 111  98]
Forma: (8,)
Dimensiones: 1
[[ 10  71  21  19 213 412 111  98]]
Forma: (1, 8)
Dimensiones: 2


In [ ]:
# new_dims = array2d.reshape(2, 4)  # cambiar las dimensiones a 2x4
# print(new_dims)
# print("Forma:", new_dims.shape)

new_dims = array2d.reshape(4, 2)  # cambiar las dimensiones a 4x2
print(new_dims)
print("Forma:", new_dims.shape)

In [ ]:
# reducir a 1D
array2d = np.arange(9).reshape(3,3)
print(array2d)

array1d = array2d.flatten()
print(array1d)


In [ ]:
# reducir
array1d = np.arange(24)
print(array1d)

array3d = array1d.reshape(2,-1, 3)
print(array3d)    # El -1 indica que debe inferir el valor
print("Forma:", array3d.shape)

## Manipulación de ndarrays

 * Cambio de ejes

In [ ]:
# Cambiar ejes
new_dims = np.arange(16).reshape(2,4,2)
print(20*'*',"Original",20*'*')
print(new_dims)

print(20*'*',"Swapped",20*'*')
swapped = new_dims.swapaxes(0,1)
# swapped = new_dims.swapaxes(0,2)
# swapped = new_dims.swapaxes(1,2)

print(swapped)
print("Forma:", swapped.shape)

 * Voltear matriz

In [ ]:
# Flip
new_dims = np.arange(16).reshape(4,4)
# print(20*'*',"Original",20*'*')
# print(new_dims)

# print(20*'*',"Flipped",20*'*')
# # print(np.flip(new_dims))
# # print(np.flip(new_dims, axis = 0))
# print(np.flip(new_dims, axis = 1))

 * Ordenar valores

In [ ]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(np.flip(array1, axis = -1))
print(array1)

 * Concatenar arrays

In [ ]:
# Juntar dos arrays
a1 = [[0,0,0],[0,0,0]]
a2 = [[1,1,1],[1,1,1]]

# print(np.hstack((a1,a2))) # una al lado de la otra
# print("Forma:",np.hstack((a1,a2)).shape)

print(np.vstack((a1,a2))) # una encima de la otra
print("Forma:",np.vstack((a1,a2)).shape)

In [ ]:
array1 = np.array([[2, 4], [6, 8]]) 
array2 = np.array([[3, 5], [7, 9]])
  
print(np.concatenate((array1, array2), axis = 1))

 * Dividir en varios arrays

In [3]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)

# arrays = np.array_split(array, 2, axis = 1)     # divide array en 2 partes iguales
# arrays = np.array_split(array, 3, axis = 0)               # divide array en 3 partes "iguales"
# arrays = np.array_split(array, [3], axis = 1)   # divide array, por la columna 3
arrays = np.array_split(array, [1,3], axis = 1) # divide array, por las columnas 1 y 3

print("Split devuelve:",type(arrays))

for i in range(len(arrays)):
    print(20*'*',"Array {}".format(i),20*'*')
    print(arrays[i])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Split devuelve: <class 'list'>
******************** Array 0 ********************
[[ 0]
 [ 4]
 [ 8]
 [12]]
******************** Array 1 ********************
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
******************** Array 2 ********************
[[ 3]
 [ 7]
 [11]
 [15]]


# Índices y slicing
- De manera análoga a índices y slicing para listas

In [ ]:
array = np.arange(10, 16)
print(array)
print(array[-1])    # acceso unidimensional
print(array[:-1])  # slice

In [ ]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # [fila, columna] Notación dimensional
print(array[2][2]) # [fila][columna] Notación anidamiento

In [ ]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[1,2,4])
print(array[1][2][4])

#### NumPy es row major

In [ ]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C')  # by default, row major
print(row_major)

In [ ]:
# Algunos lenguajes de programación son column major. Python puede adaptarse
col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F')  # col major
print(col_major)

#### Slice

In [ ]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)
print(array[1:3, 2:5]) # [row_slice, column_slice]

#### Diferencias entre índices y slicing en listas y ndarrays:
- ¡Retornan una referencia, no una copia!

In [ ]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2]  # devuelve una copia
print("Slice (copia):",my_copy)

my_copy[0] = 222
print("Slice cambia:", my_copy)
print("Original no cambia:",lista)

In [ ]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_ref = array[2:5]  # devuelve una referencia
print("Slice (referencia):", my_ref)

my_ref[0] = 222
print("Slice cambia:", my_ref)
print("Original también cambia:", array)

In [ ]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy()  # hay que hacer la copia explicitamente
print("Slice (referencia):", my_copy)

my_copy[0] = 222
print("Slice cambia:", my_copy)
print("Original no cambia:", array)

- Permite asignar valores a un corte

In [ ]:
array = np.arange(10)
print(array)

print(array[0:3])

array[0:3] = -1
print(array)

- Slicing condicionales (mask)

In [ ]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array %2 == 0
print("Mascara:", mask)
print("Valores enmascarados:", array[mask])
# print("Valores enmascarados:", array[array %2 == 0])

array[mask] = 100    # Usamos máscara para cambiar valores
print("Valores enmascarados cambian:", array)

In [ ]:
array = np.arange(-3,4)
print(array)

array[array < 0] = 0
print(array)

 * Los slicing condicionales (máscaras) ***si*** devuelven copias

In [ ]:
array = np.arange(-3,4)
mask = array % 2 == 0

array_par = array[mask]  # devuelve una copia
print("Valores enmascarados (copia):", array_par)

array_par[0] = -10
print("Valores enmascarados cambian:", array_par)
print("Original no cambia:", array)

- Acceso a múltiples valores con listados de índices

In [ ]:
array = np.arange(0,16).reshape(4,4)
print(array)
# print(array[[1,3], :])  #selecting rows
# print(array[:,[1,2]])   #selecting columns

# cross product of indexes
print(array[[1,3],:][:,[1,2]])
# print(array[np.ix_([1,3],[1,2])])  # built in ix_

# Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [ ]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)

lista += [1]
print(lista)

In [ ]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int16)
print(array)
array *= 2
print(array)

array += 10
print(array)

print(array.dtype)  # check data type of array

In [ ]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.arange(4) + 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

# print(array_1 + array_2)
# print(array_1 - array_2)
# print(array_1 * array_2)
# print(array_1 / array_2)

## Broadcasting

In [ ]:
array1= np.array([[0, 0, 0, 0],[10,10,10,10],[20,20,20,20]])
print(array1)

array2 = np.array([[1,2,3,4]])
print(array2)

print(array1 * array2)

In [29]:
video = np.arange(1024).reshape(8,8,-1)
print(video.shape)

filtro = np.full((8,8,1), 0.5)
print(filtro)

video_filtrado = video + filtro
print(video_filtrado)

(8, 8, 16)
[[[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]
  [0.5]]]
[[[5.0000e-01 1.5000e+00 2.5000e+00 ... 1.3500e+01 1.4500e+01 1.5500e+01]
  [1.6500e+01 1.7500e+01 1.8500e+01 ... 2.9500e+01 3.0500e+01 3.1500e+01]
  [3.2500e+01 3.3500e+01 3.4500e+01 ... 4.5500e+01 4.6500e+01 4.7500e+01]
  ...
  [8.0500e+01 8.1500e+01 8.2500e+01 ... 9.3500e+01 9.4500e+01 9.5500e+01]
  [9.6500e+01 9.7500e+01 9.8500e+01 ... 1.0950e+02 1.1050e+02 1.1150e+02]
  [1.1250e+02 1.1350e+02 1.1450e+02 ... 1.2550e+02 1.2650e+02 1.2750e+02]]

 [[1.2850

Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande -> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

## Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [27]:
# ejemplos de operadores
array = np.arange(5)
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [30]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])

print(array1)
print(array2)

print(np.add(video,filtro))
print(np.less_equal(array1, array2))

[0 1 2 3]
[ 0 -1  2 -3]
[[[5.0000e-01 1.5000e+00 2.5000e+00 ... 1.3500e+01 1.4500e+01 1.5500e+01]
  [1.6500e+01 1.7500e+01 1.8500e+01 ... 2.9500e+01 3.0500e+01 3.1500e+01]
  [3.2500e+01 3.3500e+01 3.4500e+01 ... 4.5500e+01 4.6500e+01 4.7500e+01]
  ...
  [8.0500e+01 8.1500e+01 8.2500e+01 ... 9.3500e+01 9.4500e+01 9.5500e+01]
  [9.6500e+01 9.7500e+01 9.8500e+01 ... 1.0950e+02 1.1050e+02 1.1150e+02]
  [1.1250e+02 1.1350e+02 1.1450e+02 ... 1.2550e+02 1.2650e+02 1.2750e+02]]

 [[1.2850e+02 1.2950e+02 1.3050e+02 ... 1.4150e+02 1.4250e+02 1.4350e+02]
  [1.4450e+02 1.4550e+02 1.4650e+02 ... 1.5750e+02 1.5850e+02 1.5950e+02]
  [1.6050e+02 1.6150e+02 1.6250e+02 ... 1.7350e+02 1.7450e+02 1.7550e+02]
  ...
  [2.0850e+02 2.0950e+02 2.1050e+02 ... 2.2150e+02 2.2250e+02 2.2350e+02]
  [2.2450e+02 2.2550e+02 2.2650e+02 ... 2.3750e+02 2.3850e+02 2.3950e+02]
  [2.4050e+02 2.4150e+02 2.4250e+02 ... 2.5350e+02 2.5450e+02 2.5550e+02]]

 [[2.5650e+02 2.5750e+02 2.5850e+02 ... 2.6950e+02 2.7050e+02 2.7150e+02

# Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o <>0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

In [ ]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

In [ ]:
# any vs all
array1 = np.arange(-8,2).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores <> 0

In [ ]:
# todas las funciones aceptan parametro 'axis' 
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
# print(array1.all(axis=0))
print(array1.all(axis=1))
# print(array1.all())

# Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multiplicación de matrices, cálculo del determinante, factorizaciones...


| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |
| *transpose(mat)* | Devuelve la transpuesta de la matrix |

In [ ]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)

print(20*'*',"Matriz A",20*'*')
print(A)
print(20*'*',"Matriz B",20*'*')
print(B)

print(20*'*',"Solución",20*'*')
# print(np.matmul(A, B))
# print(np.dot(A, B))
print(A @ B)

In [31]:
import numpy.linalg as linalg
#-----------------------------------------OJO examen
# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x

A = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])
b = np.array([12,2,32])

print(A)
print(b)
x,y,z = linalg.solve(A,b)
print(f'x={x} y={y} z={z}')

verify = np.allclose(A @ np.array([x,y,z]), b)
print(verify)

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True


In [ ]:
#matriz identidad
I = np.identity(4) # similar a np.eye()
print(I)

A = np.arange(16).reshape(4,4)
print(A)
print(np.matmul(A,I))

# Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [ ]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)

clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, abs(bank_transfers_values))
print(clean_data)

In [ ]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

In [ ]:
# np.where puede seleccionar elementos igual que una máscara
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)

credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True
print(credits)
print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]
# print(bank_transfers_values[bank_transfers_values > 0])

In [ ]:
# valor de array dependiendo del valor en array referencia
array1 = np.arange(6)
print("Array 1:", array1)

array2 = np.arange(6) * 10
print("Array 2:", array2)

ref_array = np.array([0, 3, -1, 6, -12, -2])
print("Ref Array:", ref_array)

final_array = np.where(ref_array > 0, array1, array2)
print("Final Array:", final_array)

# Números aleatorios
- Python módulo random

In [ ]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores

In [ ]:
# elegir un elemento al azar dentro de una colección
names = ['Bulbasaur','Charmander','Squirtle']
random.choice(names)

## NumPy.random
- Generar fácilmente listas con valores aleatorios

In [ ]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores 
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

In [ ]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

In [ ]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
# print(np.random.uniform(low=0, high=10)) # distribución uniforme
# print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

## Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [ ]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())

# print()    
    
# for i in range(6):
#     np.random.seed(i) # diferentes semillas
#     print(np.random.rand())
#     print(np.random.rand())

# Escritura y lectura de ndarrays a archivos 
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [ ]:
# escribir a archivo
import os
ruta = os.path.join("res" ,"o_values_array.npy")

values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)

In [ ]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

In [ ]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")

values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz   

In [ ]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)

print(type(npzfile.files))
print(npzfile.files)

for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
     print(npzfile[key])

### ¿Por qué molestarse con .npy?
- Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
- ¿Para qué escribir los datos de nuevo?

In [ ]:
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)

ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [ ]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data,  dtype = np.int8).reshape(1000,1000)

In [ ]:
%%timeit
data = np.load(ruta_npy)

In [ ]:
%%timeit
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")

### velocidad + simplicidad vs memoria

## Ejercicios

- Ejercicios para practicar NumPy: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
- Con pistas: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints.md
- Soluciones en: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md